### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by jerbear64** [nicohman/eidolon#3]
Eidolon fails to work properly on Fedora 27. This occurs on builds with nightly, beta and stable Rust, as well as from cargo directly, and with a precompiled binary. This doesn't appear to happen with version 1.1, but I've been able to replicate the crash on 1.2 and the latest Git commit.

The crash only occurs after first-time registry initialization has happened.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: eidolon::interpret_args
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  13: __libc_start_main
```

**Comment by nicohman** [comment]
First off: Thanks for leaving an issue! Second off, yeah, it does crash. Am currently taking a look and will  fix it ASAP. My apologies!

**Comment by nicohman** [comment]
Okay, could you try again with the latest git commit? I've tried it in a new environment and it appears to work fine now.
